name: Tworzenie.exe

on:
  push:
    branches:
      - mian
  schedule:
    - cron: "37 21 * * 0" # Uruchomienie raz w tygodniu 21:37 w niedzielę
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest #zmiana domyślnego serwera na Windowsa
    
    steps:
    - name: Sprawdź repozytorium/ pobieranie aby mieć do niego dostęp 
      uses: actions/checkout@v3

    - name: Skonfiguruj Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.9.5" # Wybierz odpowiednią wersję Pythona

    - name: Zainstaluj zależności
      shell: pwsh
      run: ./Instalator.ps1
      
    - name: Odpalenie skryptu
      run: python Task.py
      
    - name: Przesyłanie utworzonego pliku
      uses: actions/upload-artifact@v3
      with:
        name: Converter.exe
        path: ${{ github.workspace }}/Task.exe
